collections_dir: our_collections
collections:
  members:
    output: true
  publications:
    output: true

defaults:
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"

exclude: 
  - tmp/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag